# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields
import web_clientes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('logo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=web_clientes.models.Cliente.imagen_upload_to, verbose_name='Logo Aliado')),
            ],
        ),
    ]
