# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
