# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 15:04
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields
import web_clientes.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_clientes', '0002_cliente_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=web_clientes.models.Cliente.imagen_upload_to, verbose_name='Logo Cliente'),
        ),
    ]
