# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-05-15 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_clientes', '0003_auto_20171030_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteIndustria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='industria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_clientes.ClienteIndustria'),
        ),
    ]
