# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-05-15 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_clientes', '0004_auto_20200515_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='industria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='web_clientes.ClienteIndustria'),
        ),
    ]
