# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-06 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_clientes', '0005_auto_20200515_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteindustria',
            name='nombre_en',
            field=models.CharField(default='Set english name', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clienteindustria',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
