# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_contactos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientecontacto',
            name='nro_contacto',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
