# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields
import web_empresa.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaFotoEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('icono', models.CharField(max_length=40)),
                ('imagen', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=web_empresa.models.GaleriaFotoEmpresa.imagen_upload_to, verbose_name='Imagen principal galería')),
            ],
        ),
    ]
