# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_empresa', '0003_galeriafotoempresaimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriafotoempresa',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
