# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_empresa', '0004_galeriafotoempresa_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeriafotoempresa',
            options={'verbose_name': 'Galería de Fotos Empresa', 'verbose_name_plural': 'Galerías de Fotos Emperesa'},
        ),
        migrations.AlterField(
            model_name='galeriafotoempresa',
            name='icono',
            field=models.CharField(help_text='Encontrar en http://fontawesome.io/', max_length=40),
        ),
        migrations.AlterField(
            model_name='galeriafotoempresaimagen',
            name='galeria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_imagenes', to='web_empresa.GaleriaFotoEmpresa'),
        ),
    ]
