# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_empresa', '0005_auto_20170927_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriafotoempresaimagen',
            name='marca_agua',
            field=models.PositiveIntegerField(choices=[(0, 'Ninguna'), (1, 'Blanca'), (2, 'Naranja')], default=0),
        ),
    ]
