# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_empresa', '0007_auto_20171004_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriafotoempresa',
            name='marca_agua',
            field=models.PositiveIntegerField(choices=[(0, 'Ninguna'), (1, 'Blanca'), (2, 'Naranja')], default=2),
        ),
    ]
