# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-11 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_empresa', '0012_auto_20171102_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliado',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
