# Generated by Django 3.2.12 on 2022-04-07 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_empresa', '0013_aliado_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeriafotoempresaimagen',
            name='galeria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_imagenes', to='web_empresa.galeriafotoempresa'),
        ),
    ]
