version: '2'

services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: odecopack-web-mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: user
    command: --init-file /data/application/init.sql
    ports:
      - 3306:3306
    volumes:
      - ./volumes/mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/data/application/init.sql

  redis:
    image: redis:6.2
    container_name: odecopack-web-redis
    ports:
      - 6379:6379