# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields
import tinymce.models
import web_configurations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(default='Dirección aquí', max_length=200, verbose_name='Dirección')),
                ('horarios_de_atencion', tinymce.models.HTMLField(default='Texto Horarios de Atención aquí', verbose_name='Horarios de Atención')),
                ('numeros_contacto', models.TextField(blank=True, max_length=20, null=True, verbose_name='Numeros de Contacto')),
                ('correos_contacto', models.TextField(blank=True, max_length=20, null=True, verbose_name='Numeros de Contacto')),
            ],
            options={
                'verbose_name': 'General',
            },
        ),
        migrations.CreateModel(
            name='IndexConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_titulo', models.CharField(default='Aqui el titulo', max_length=150)),
                ('header_text', models.TextField(default='Aqui la descripción', max_length=150)),
            ],
            options={
                'verbose_name': 'Index',
            },
        ),
        migrations.CreateModel(
            name='LaEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Aqui el titulo', max_length=150)),
                ('texto', tinymce.models.HTMLField(default='Aqui la descripción', verbose_name='Horarios de Atención')),
                ('imagen_principal', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=web_configurations.models.LaEmpresaConfiguration.imagen_principal_upload_to, verbose_name='Imagen Principal')),
            ],
            options={
                'verbose_name': 'Index',
            },
        ),
    ]
