# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 16:13
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_configurations', '0002_indexconfiguration_header_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalconfiguration',
            name='correos_contacto',
            field=tinymce.models.HTMLField(blank=True, default='Correos de contacto', null=True, verbose_name='Correos de Contacto'),
        ),
        migrations.AlterField(
            model_name='generalconfiguration',
            name='numeros_contacto',
            field=tinymce.models.HTMLField(blank=True, default='Numeros de contacto', null=True, verbose_name='Numeros de Contacto'),
        ),
    ]
