# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_configurations', '0005_auto_20170927_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexconfiguration',
            name='header_text',
            field=models.TextField(blank=True, default='Aqui la descripción', max_length=150, null=True),
        ),
    ]
