# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_configurations', '0009_cacheconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacheconfiguration',
            name='nombre_cache_clientes',
            field=models.CharField(default='cache inicial clientes', help_text='Cambiar por cada cambio en Clientes', max_length=10, verbose_name='Clientes Nombre Cache'),
        ),
        migrations.AlterField(
            model_name='cacheconfiguration',
            name='nombre_cache_empresa',
            field=models.CharField(default='cache inicial empresa', help_text='Cambiar por cada cambio en Empresa, Aliados o Galeria Empresa', max_length=10, verbose_name='Empresa Nombre Cache'),
        ),
    ]
