# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_configurations', '0010_auto_20171006_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='cacheconfiguration',
            name='tiempo_cache_empresa',
            field=models.PositiveIntegerField(default=86400, verbose_name='Empresa Tiempo Cache'),
        ),
    ]
