# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_configurations', '0012_cacheconfiguration_tiempo_cache_clientes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cacheconfiguration',
            options={'verbose_name': 'Cache Index'},
        ),
        migrations.AddField(
            model_name='cacheconfiguration',
            name='nombre_cache_index_header',
            field=models.CharField(default='Index Header', help_text='Cambiar por cada cambio en Index Header', max_length=40, verbose_name='Index Header Nombre Cache'),
        ),
        migrations.AddField(
            model_name='cacheconfiguration',
            name='tiempo_cache_index_header',
            field=models.PositiveIntegerField(default=86400, verbose_name='Index Header Tiempo Cache'),
        ),
        migrations.AlterField(
            model_name='cacheconfiguration',
            name='nombre_cache_clientes',
            field=models.CharField(default='cache inicial clientes', help_text='Cambiar por cada cambio en Clientes', max_length=40, verbose_name='Clientes Nombre Cache'),
        ),
        migrations.AlterField(
            model_name='cacheconfiguration',
            name='nombre_cache_empresa',
            field=models.CharField(default='cache inicial empresa', help_text='Cambiar por cada cambio en Empresa, Aliados o Galeria Empresa', max_length=40, verbose_name='Empresa Nombre Cache'),
        ),
    ]
