# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_configurations', '0012_cacheconfiguration_tiempo_cache_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cacheconfiguration',
            name='nombre_cache_index_header',
            field=models.CharField(default='Index Header', help_text='Cambiar por cada cambio en Index Header', max_length=10, verbose_name='Index Header Nombre Cache'),
        ),
        migrations.AddField(
            model_name='cacheconfiguration',
            name='tiempo_cache_index_header',
            field=models.PositiveIntegerField(default=86400, verbose_name='Index Header Tiempo Cache'),
        ),
    ]
