# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_configurations', '0014_cacheconfiguration_empresa_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cacheconfiguration',
            name='nombre_cache_empresa',
        ),
        migrations.RemoveField(
            model_name='cacheconfiguration',
            name='tiempo_cache_empresa',
        ),
        migrations.AddField(
            model_name='cacheconfiguration',
            name='clientes_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
