# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_configurations', '0015_auto_20171006_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cacheconfiguration',
            name='nombre_cache_clientes',
        ),
        migrations.RemoveField(
            model_name='cacheconfiguration',
            name='tiempo_cache_clientes',
        ),
    ]
