# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_configurations', '0015_auto_20171006_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacheconfiguration',
            name='nombre_cache_index_header',
            field=models.CharField(default='Index Header', help_text='Cambiar por cada cambio en Index Header', max_length=40, verbose_name='Index Header Nombre Cache'),
        ),
    ]
