# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_configurations', '0017_auto_20171006_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='cacheconfiguration',
            name='soluciones_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
