# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_configurations', '0018_cacheconfiguration_soluciones_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfiguration',
            name='version_css_cache',
            field=models.CharField(default='', max_length=20),
        ),
    ]
