# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_configurations', '0019_generalconfiguration_version_css_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='laempresaconfiguration',
            name='video',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
