# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields
import web_configurations.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_configurations', '0020_laempresaconfiguration_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexconfiguration',
            name='overlay_publicidad',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=web_configurations.models.IndexConfiguration.header_imagen_upload_to, verbose_name='Imagen Overlay Publicidad (1920 x 1080)'),
        ),
        migrations.AddField(
            model_name='indexconfiguration',
            name='overlay_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
