# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 15:04
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields
import web_configurations.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_configurations', '0021_auto_20171027_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexconfiguration',
            name='overlay_publicidad',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=web_configurations.models.IndexConfiguration.header_imagen_upload_to, verbose_name='Imagen Overlay Publicidad (1024 x 768)'),
        ),
    ]
