# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields
import web_configurations.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_configurations', '0022_auto_20171030_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasosExitoConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_titulo', models.CharField(default='Aqui el titulo', max_length=150)),
                ('header_text', models.TextField(blank=True, default='Aqui la descripción', max_length=150, null=True)),
                ('header_imagen', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=web_configurations.models.CasosExitoConfiguration.header_imagen_upload_to, verbose_name='Imagen Cabezote (2560 x 1500)')),
            ],
            options={
                'verbose_name': 'Casos Exito',
            },
        ),
    ]
