# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 15:39
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_configurations', '0023_casosexitoconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='casosexitoconfiguration',
            name='descripcion',
            field=tinymce.models.HTMLField(blank=True, default='Descripción casos Éxito', null=True, verbose_name='Texto Casos Éxito'),
        ),
    ]
