# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 20:32
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_configurations', '0024_casosexitoconfiguration_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='laempresaconfiguration',
            name='texto_en',
            field=tinymce.models.HTMLField(default='Aqui la descripción en ingles', verbose_name='Descripcion Empresa Ingles'),
        ),
        migrations.AlterField(
            model_name='laempresaconfiguration',
            name='texto',
            field=tinymce.models.HTMLField(default='Aqui la descripción', verbose_name='Descripcion Empresa'),
        ),
    ]
