# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 15:40
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_configurations', '0025_auto_20171227_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfiguration',
            name='horarios_de_atencion_en',
            field=tinymce.models.HTMLField(default='Texto Horarios de Atención aquí', verbose_name='Horarios de Atención Ingles'),
        ),
    ]
