# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_configurations', '0026_generalconfiguration_horarios_de_atencion_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexconfiguration',
            name='header_text_en',
            field=models.TextField(blank=True, default='Aqui la descripción Ingles', max_length=150, null=True),
        ),
    ]
