# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_configurations', '0027_indexconfiguration_header_text_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casosexitoconfiguration',
            name='header_titulo',
        ),
        migrations.AddField(
            model_name='casosexitoconfiguration',
            name='header_text_en',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Titulo Ingles'),
        ),
        migrations.AlterField(
            model_name='casosexitoconfiguration',
            name='header_text',
            field=models.TextField(blank=True, default='Aqui la descripción', max_length=150, null=True, verbose_name='Titulo'),
        ),
    ]
