# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-01-31 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields
import web_configurations.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_configurations', '0032_auto_20190304_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfiguration',
            name='whatsaap',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='indexconfiguration',
            name='overlay_publicidad',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=web_configurations.models.IndexConfiguration.overlay_publicidad_imagen_upload_to, verbose_name='Imagen Overlay Publicidad (1024 x 768)'),
        ),
    ]
