# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-06 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_configurations', '0033_auto_20200131_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfiguration',
            name='copyright',
            field=models.CharField(blank=True, default='© 2021 Copyright: Odecopack', max_length=80, null=True),
        ),
    ]
