# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-07 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_configurations', '0036_auto_20220406_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalconfiguration',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección'),
        ),
    ]
