# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_casos_exito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casoexito',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
