# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_casos_exito', '0002_casoexito_fecha_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoExitoTestimonio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_persona', models.CharField(max_length=200)),
                ('testimonio', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
