# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_casos_exito', '0003_casoexitotestimonio'),
    ]

    operations = [
        migrations.AddField(
            model_name='casoexitotestimonio',
            name='caso_exito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mis_testimonios', to='web_casos_exito.CasoExito'),
            preserve_default=False,
        ),
    ]
