# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_clientes', '0003_auto_20171030_1004'),
        ('web_casos_exito', '0006_auto_20171215_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='casoexito',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web_clientes.Cliente', verbose_name='mis_casos_exito'),
            preserve_default=False,
        ),
    ]
