# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_casos_exito', '0007_casoexito_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casoexito',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mis_casos_exito', to='web_clientes.Cliente'),
        ),
    ]
