# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_casos_exito', '0008_auto_20171215_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='casoexitotestimonio',
            name='cargo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
