# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-03 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_casos_exito', '0010_auto_20171219_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='casoexito',
            name='descripcion_corta_en',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Corta Ingles'),
        ),
        migrations.AddField(
            model_name='casoexito',
            name='descripcion_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Descripción Ingles'),
        ),
        migrations.AddField(
            model_name='casoexito',
            name='nombre_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre en Ingles'),
        ),
        migrations.AddField(
            model_name='industriacasoexito',
            name='nombre_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre en Ingles'),
        ),
        migrations.AlterField(
            model_name='casoexito',
            name='descripcion_corta',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Corta'),
        ),
        migrations.AlterField(
            model_name='casoexito',
            name='nombre',
            field=models.CharField(max_length=120, verbose_name='Nombre'),
        ),
    ]
