# Generated by Django 3.2.12 on 2022-04-07 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_clientes', '0007_alter_cliente_industria'),
        ('web_casos_exito', '0011_auto_20180103_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casoexito',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mis_casos_exito', to='web_clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='casoexito',
            name='industria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_casos_exito', to='web_casos_exito.industriacasoexito'),
        ),
        migrations.AlterField(
            model_name='casoexitoimagen',
            name='caso_exito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_imagenes', to='web_casos_exito.casoexito'),
        ),
        migrations.AlterField(
            model_name='casoexitotestimonio',
            name='caso_exito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_testimonios', to='web_casos_exito.casoexito'),
        ),
        migrations.AlterField(
            model_name='casoexitovideo',
            name='caso_exito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_videos', to='web_casos_exito.casoexito'),
        ),
    ]
