# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields
import tinymce.models
import web_soluciones.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('texto', tinymce.models.HTMLField(blank=True, default='Descripción de esta solución', null=True, verbose_name='Texto Soluciones')),
                ('boton_soluciones', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=web_soluciones.models.Solucion.imagen_boton_upload_to, verbose_name='Imagen Boton')),
            ],
        ),
    ]
