# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solucion',
            options={'verbose_name': 'Solución', 'verbose_name_plural': 'Soluciones'},
        ),
        migrations.AddField(
            model_name='solucion',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
