# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import tinymce.models
import web_soluciones.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0002_auto_20170926_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSolucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion_corta', models.TextField()),
                ('mas', tinymce.models.HTMLField(blank=True, default='Descripción de este Item', null=True, verbose_name='Texto Soluciones')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('boton_soluciones', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=web_soluciones.models.ItemSolucion.imagen_principal_upload_to, verbose_name='Imagen Item Solución')),
                ('solucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_items', to='web_soluciones.Solucion')),
            ],
        ),
    ]
