# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0003_itemsolucion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemsolucion',
            options={'verbose_name': 'Item Solución', 'verbose_name_plural': 'Items Soluciones'},
        ),
        migrations.AddField(
            model_name='solucion',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
