# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 16:13
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields
import web_soluciones.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0006_auto_20170926_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='solucion',
            name='header_imagen',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=web_soluciones.models.Solucion.header_imagen_upload_to, verbose_name='Imagen Cabezote'),
        ),
    ]
