# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0007_solucion_header_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemsolucion',
            old_name='boton_soluciones',
            new_name='imagen_principal',
        ),
    ]
