# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0009_itemsolucionimagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsolucionimagen',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
