# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields
import web_soluciones.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0010_auto_20170926_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsolucion',
            name='imagen_principal',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=web_soluciones.models.ItemSolucion.imagen_principal_upload_to, verbose_name='Imagen Item Solución (400x200)'),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='descripcion_corta',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
