# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0011_auto_20170929_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solucion',
            name='descripcion_corta',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
