# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0014_auto_20170929_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsolucion',
            name='categoria',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='itemsolucion',
            name='categoria_dos',
            field=models.CharField(default='', max_length=120),
        ),
    ]
