# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0017_auto_20170929_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsolucion',
            name='categoria',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
