# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0018_auto_20170929_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsolucion',
            name='descripcion_corta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
