# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 18:25
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields
import web_soluciones.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0021_auto_20171004_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='solucion',
            name='boton_soluciones_index',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=web_soluciones.models.Solucion.imagen_boton_upload_to, verbose_name='Imagen Boton Index'),
        ),
    ]
