# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0023_auto_20171006_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='solucion',
            name='icono_class',
            field=models.CharField(default='', max_length=100),
        ),
    ]
