# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0024_solucion_icono_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solucion',
            name='boton_soluciones',
        ),
        migrations.RemoveField(
            model_name='solucion',
            name='boton_soluciones_index',
        ),
    ]
