# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0025_auto_20171009_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsolucionimagen',
            name='item_solucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_imagenes', to='web_soluciones.ItemSolucion'),
        ),
    ]
