# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0026_auto_20171017_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsolucion',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
