# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import web_soluciones.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0027_itemsolucion_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to=web_soluciones.models.Documento.documento_upload)),
                ('nombre', models.CharField(max_length=120)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('icono', models.CharField(max_length=120)),
                ('solucion', models.ManyToManyField(related_name='mis_documentos', to='web_soluciones.Solucion')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
