# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0028_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
