# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0029_documento_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='solucion',
        ),
        migrations.AddField(
            model_name='documento',
            name='item_solucion',
            field=models.ManyToManyField(related_name='mis_documentos', to='web_soluciones.ItemSolucion'),
        ),
    ]
