# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0032_auto_20171102_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsoluciontagseo',
            name='item_solucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_tags', to='web_soluciones.ItemSolucion'),
        ),
    ]
