# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0033_auto_20171102_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsolucion',
            name='alt_seo',
        ),
        migrations.AddField(
            model_name='itemsolucionimagen',
            name='alt_seo',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
