# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0039_auto_20171129_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsolucion',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
