# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0040_itemsolucion_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsolucion',
            name='slug',
        ),
    ]
