# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0041_remove_itemsolucion_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solucion',
            name='nombre',
            field=models.CharField(max_length=120, verbose_name='Nombre'),
        ),
    ]
