# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0042_auto_20171227_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='solucion',
            name='nombre_en',
            field=models.CharField(default='Nombre en Ingles', max_length=120, verbose_name='Nombre en ingles'),
        ),
    ]
