# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 17:03
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0043_solucion_nombre_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solucion',
            name='descripcion_corta',
        ),
        migrations.AddField(
            model_name='solucion',
            name='texto_en',
            field=tinymce.models.HTMLField(blank=True, default='Descripción de esta solución en Ingles', null=True, verbose_name='Texto Soluciones Ingles'),
        ),
    ]
