# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0044_auto_20171228_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsolucion',
            name='descripcion_corta_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemsolucion',
            name='mas_en',
            field=tinymce.models.HTMLField(blank=True, default='Descripción de este Item en Ingles', null=True, verbose_name='Texto Item Solución en Ingles'),
        ),
        migrations.AddField(
            model_name='itemsolucion',
            name='nombre_en',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='itemsolucion',
            name='mas',
            field=tinymce.models.HTMLField(blank=True, default='Descripción de este Item', null=True, verbose_name='Texto Item Solución'),
        ),
    ]
