# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 17:33
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0046_auto_20171228_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsolucion',
            name='mas_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Texto Item Solución en Ingles'),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='texto_en',
            field=tinymce.models.HTMLField(blank=True, default='Descripción de esta solución en Ingles', null=True, verbose_name='Texto Soluciones Ingles'),
        ),
    ]
