# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-29 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0047_auto_20171228_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaItemSolucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('nombre', models.CharField(max_length=120)),
                ('nombre_en', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='itemsolucion',
            name='categoria_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mis_items', to='web_soluciones.CategoriaItemSolucion'),
        ),
    ]
