# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-29 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0048_auto_20171229_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaitemsolucion',
            options={'verbose_name': 'Categoría Item Solucion', 'verbose_name_plural': 'Categorías Items Soluciones'},
        ),
        migrations.AlterField(
            model_name='categoriaitemsolucion',
            name='nombre',
            field=models.CharField(default='', max_length=120),
        ),
    ]
