# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-29 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0050_auto_20171229_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaitemsolucion',
            name='nombre',
            field=models.CharField(blank=True, default=' ', max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='categoriaitemsolucion',
            name='nombre_en',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='categoriaitemsolucion',
            name='orden',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
