# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-06 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0053_auto_20171229_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsolucionimagen',
            name='alt_seo_en',
            field=models.CharField(blank=True, default='', max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='itemsolucionimagen',
            name='descripcion_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
