# Generated by Django 3.2.12 on 2022-04-07 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0054_auto_20220406_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsolucion',
            name='categoria_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mis_items', to='web_soluciones.categoriaitemsolucion'),
        ),
        migrations.AlterField(
            model_name='itemsolucionimagen',
            name='item_solucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_imagenes', to='web_soluciones.itemsolucion'),
        ),
        migrations.AlterField(
            model_name='itemsolucionvideo',
            name='item_solucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_videos', to='web_soluciones.itemsolucion'),
        ),
    ]
