# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-07 16:04
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0055_auto_20220407_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsolucionimagen',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='itemsolucionimagen',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
