# Generated by Django 4.0.4 on 2022-04-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0056_auto_20220407_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='solucion',
            name='slug_en',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
