# Generated by Django 4.0.4 on 2022-04-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0059_remove_itemsolucionimagen_slug_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='en_espanol',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='en_ingles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documento',
            name='nombre_en',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='itemsolucionvideo',
            name='espanol',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='itemsolucionvideo',
            name='ingles',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documento',
            name='nombre',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
