# Generated by Django 4.0.4 on 2022-04-16 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0060_documento_en_espanol_documento_en_ingles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemsolucionvideo',
            old_name='espanol',
            new_name='en_espanol',
        ),
        migrations.RenameField(
            model_name='itemsolucionvideo',
            old_name='ingles',
            new_name='en_ingles',
        ),
    ]
