# Generated by Django 4.0.4 on 2022-04-16 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_soluciones', '0061_rename_espanol_itemsolucionvideo_en_espanol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='activo',
        ),
    ]
